version: "3"
 
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
     - 80:80
    volumes:
     - /data/www:/usr/share/nginx/html
     - /data/nginx/conf.d:/etc/nginx/conf.d
  php:
    image: bitnami/php-fpm:7.3
    container_name: php-fpm
    volumes:
     - /data/www:/var/www/html
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=123456
